name: CI Pipeline

on:
  push:
    branches:
      - '**'  # Trigger on any branch
  pull_request:
    branches:
      - '**'  # Trigger on pull request to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}  # Set the environment variable for the test step
      run: |
        pytest
